### PR TITLE
Allow compilation on Java 8 and small fixes

### PR DESCRIPTION
**Pull request by petervandenabeele**
- Allows the compilation on Java 8
- Some clarification in the README make it easier to get started
- Small fixes

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks @petervandenabeele ! Can you sign our CLA please: https://github.com/snowplow/snowplow/wiki/CLA

**Comment by petervandenabeele** [comment]
Done.

**Comment by alexanderdean** [comment]
Confirmed!

**Comment by petervandenabeele** [comment]
bump ...

Any chance to get this merged or improvements required ?

Many Thx,

Peter

**Comment by alexanderdean** [comment]
Merged and released! Thanks so much.

**Comment by petervandenabeele** [comment]
Thanks (and sorry for the oversight the my.conf was covered).
Regarding the .idea ignore, I fixed this now with a dedicated
`.gitignore_global_with_idea` using for this project.

**Comment by alexanderdean** [comment]
No worries at all - thanks again @petervandenabeele !

**Pull request merged**
